### ISSUE TITLE
Add original intro video?

### ISSUE THREAD

**Issue by LordBlacksun** [FreeAllegiance/Allegiance-AZ#1]
I upscaled the original intro video to 1080p. If need be, we can add it, so that it displays, everytime Allegiance launches.
Thoughts?

**Comment by BackTrak** [comment]
There is a video currently playing every time allegiance launches, is this already done?

**Comment by LordBlacksun** [comment]
That is just the MSRG logo.
ill upload the video here from my dropbox.

**Comment by LordBlacksun** [comment]
https://www.dropbox.com/s/5a5zpvu4ugu7emx/INTRO.zip?dl=0
Here it is. closing this
