### ISSUE TITLE
Add high resolution textures support

### ISSUE THREAD

**Issue by LordBlacksun** [FreeAllegiance/Allegiance-AZ#2]
I still have the high resolution pack, that I sent to PKK in April for our installer.
Is it a problem, if I include it in the 1.3 installer?

**Comment by LordBlacksun** [comment]
https://www.dropbox.com/s/zcl6v54gahl4zk2/NEW%20HIGH%20RES%20TEXTURE%20PACK%20FOR%20R8.zip?dl=0
^ posting here as well

**Comment by Astn** [comment]
Not sure why I never noticed this.. I think it's a great idea. :+1:

**Comment by LordBlacksun** [comment]
Well I am dumb,  the high res textures support is already in our latest bulid.

**Comment by LordBlacksun** [comment]
Future release closing for now
